export const SET_COVID_DATA = 'SET_COVID_DATA';
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
export const SET_CURRENT_UNIT = 'SET_CURRENT_UNIT';
export const SET_CURRENT_COUNTRY = 'SET_CURRENT_COUNTRY';
export const SET_CURRENT_PERIOD = 'SET_CURRENT_PERIOD';
